services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_USER: prediction
      POSTGRES_PASSWORD: prediction
      POSTGRES_DB: prediction
    ports:
      - "5433:5432"  # порт 5433 на хосте → 5432 в контейнере
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prediction -d prediction"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8082:8082"
    environment:
      CONFIG_PATH: /app/config/local.yaml
      DB_HOST: postgres
      DB_PORT: 5432
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./front
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge