version: '3.9'

services:
  postgres-db:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_USER: prediction
      POSTGRES_PASSWORD: prediction
      POSTGRES_DB: prediction
    ports:
      - "5433:5432"