env: "local" # local, dev, prod
storage_path:
  username: ""
  password: ""
  host: ""
  port:
  database: ""
  ssl_mode: "disable"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s