env: "local" # local, dev, prod
storage_path:
  username: "prediction"
  password: "prediction"
  host: "localhost"
  port: 5433
  database: "prediction"
  ssl_mode: "disable"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s